#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

#define WIFI_SSID      "Quang Trung"
#define WIFI_PASSWORD  "0913048530"

#define WIFI_RETRY_BASE_DELAY_MS 1000
#define WIFI_RETRY_MAX_DELAY_MS  30000

#endif